[project]
name = "token-sync"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.auth-manager]
path = "contracts/auth-manager.clar"
depends_on = []

[contracts.event-tracker]
path = "contracts/event-tracker.clar"
depends_on = []

[contracts.token-registry]
path = "contracts/token-registry.clar"
depends_on = []

[contracts.token-synchronizer]
path = "contracts/token-synchronizer.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
